import { Outfit, Ovo } from "next/font/google";
import './globals.css';

const outfit = Outfit({
  subsets: ["latin"], weight: ["400", "500", "600", "700"],
});

const ovo = Ovo({
  subsets: ["latin"], weight: ["400"],
});

export const metadata = {
  title: "Portfolio - JiraphatSri",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${outfit.className} ${ovo.className} antialiased leading-8 overflow-x-hidde dark:text-white dark:bg-[#11001F]` }
      >
        {children}
      </body>
    </html>
  );
}
